
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine версии 17.1.0+ae57d105c для .NET Framework
      (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
      
      Сборка начата 08.10.2023 8:23:46.
      Проект "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.77
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/3.27.7/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine версии 17.1.0+ae57d105c для .NET Framework
      (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
      
      Сборка начата 08.10.2023 8:23:47.
      Проект "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\3.27.7\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\3.27.7\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\3.27.7\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.60
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/3.27.7/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/alex/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-cqmad2"
      binary: "C:/Users/alex/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-cqmad2"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-cqmad2'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_6e134.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Microsoft (R) Build Engine версии 17.1.0+ae57d105c для .NET Framework
        (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
        
        Сборка начата 08.10.2023 8:23:48.
        Проект "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-cqmad2\\cmTC_6e134.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_6e134.dir\\Debug\\".
          Создание каталога "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-cqmad2\\Debug\\".
          Создание каталога "cmTC_6e134.dir\\Debug\\cmTC_6e134.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_6e134.dir\\Debug\\cmTC_6e134.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_6e134.dir\\Debug\\\\" /Fd"cmTC_6e134.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Downloads\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.31.31104 для x64
          CMakeCCompilerABI.c
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_6e134.dir\\Debug\\\\" /Fd"cmTC_6e134.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Downloads\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-cqmad2\\Debug\\cmTC_6e134.exe" /INCREMENTAL /ILK:"cmTC_6e134.dir\\Debug\\cmTC_6e134.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-cqmad2/Debug/cmTC_6e134.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-cqmad2/Debug/cmTC_6e134.lib" /MACHINE:X64  /machine:x64 cmTC_6e134.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_6e134.vcxproj -> C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-cqmad2\\Debug\\cmTC_6e134.exe
        FinalizeBuildStatus:
          Файл "cmTC_6e134.dir\\Debug\\cmTC_6e134.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_6e134.dir\\Debug\\cmTC_6e134.tlog\\cmTC_6e134.lastbuildstate".
        Сборка проекта "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-cqmad2\\cmTC_6e134.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.55
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Downloads/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/alex/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-4h3fgl"
      binary: "C:/Users/alex/OneDrive/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-4h3fgl"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-4h3fgl'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_77471.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Microsoft (R) Build Engine версии 17.1.0+ae57d105c для .NET Framework
        (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
        
        Сборка начата 08.10.2023 8:23:49.
        Проект "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-4h3fgl\\cmTC_77471.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_77471.dir\\Debug\\".
          Создание каталога "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-4h3fgl\\Debug\\".
          Создание каталога "cmTC_77471.dir\\Debug\\cmTC_77471.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_77471.dir\\Debug\\cmTC_77471.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_77471.dir\\Debug\\\\" /Fd"cmTC_77471.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Downloads\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.31.31104 для x64
          CMakeCXXCompilerABI.cpp
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_77471.dir\\Debug\\\\" /Fd"cmTC_77471.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Downloads\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-4h3fgl\\Debug\\cmTC_77471.exe" /INCREMENTAL /ILK:"cmTC_77471.dir\\Debug\\cmTC_77471.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-4h3fgl/Debug/cmTC_77471.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/alex/OneDrive/Рабочий стол/Laba_1_Alg/laba_1/CMakeFiles/CMakeScratch/TryCompile-4h3fgl/Debug/cmTC_77471.lib" /MACHINE:X64  /machine:x64 cmTC_77471.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_77471.vcxproj -> C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-4h3fgl\\Debug\\cmTC_77471.exe
        FinalizeBuildStatus:
          Файл "cmTC_77471.dir\\Debug\\cmTC_77471.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_77471.dir\\Debug\\cmTC_77471.tlog\\cmTC_77471.lastbuildstate".
        Сборка проекта "C:\\Users\\alex\\OneDrive\\Рабочий стол\\Laba_1_Alg\\laba_1\\CMakeFiles\\CMakeScratch\\TryCompile-4h3fgl\\cmTC_77471.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.52
        
      exitCode: 0
...
